#!/usr/bin/env ruby

if ARGV[0] == "1"
  system("nm-connection-editor")
end

# parses the nmcli connections
interfaces = `nmcli -t connection show --active`
  .split("\n")
  .map do |interface_string|
  values = interface_string.split(":")
  {
    name: values[0],
    uuid: values[1],
    type: values[2],
    device: values[3],
  }
end

# filter relevant connections
interfaces.select! { |iface| ["802-11-wireless", "ethernet", "802-3-ethernet", "vpn"].include? iface[:type] }

# get connection status
interfaces.map! do |iface|
  device = `nmcli -t device status`
    .split("\n")
    .map { |line| line.split(":") }
    .select { |device| device[0] == iface[:device] }[0]
  iface[:status] = device[2]
  iface
end

# get ip address from connextion
interfaces.map! do |iface|
  info = `nmcli -t --fields connection,IP4 connection show "#{iface[:uuid]}"`
  ip = /^IP4\.ADDRESS\[1\]:(.+)\/\d{1,2}$/.match(info)
  iface[:ip] = ip[1] unless ip.nil?
  iface
end

# create output
interfaces.map! do |iface|
  "<span color='lightgreen'>#{iface[:name]}</span> #{iface[:status].include?("connected") ? iface[:ip] : iface[:status]}"
end

puts "🖧  #{interfaces.length > 0 ? interfaces.join(" | ") : "<span color='red'>not connected</span>"}"
