#!/usr/bin/env ruby
require "curb"

if ARGV[0] == "1"
  begin
    http = Curl.get "https://ipecho.net/plain"
  rescue => exception
    puts ""
  else
    puts "🌍 #{http.body_str}"
  end
else
  puts "-> 🌍 <-"
end
