#!/usr/bin/env ruby

layout_path = "#{Dir.home}/.config/layouts"
modes = Dir.entries(layout_path)
.reject{ |file| File.directory? file || file == "." || file == ".." }

selected = ARGV[0]
if modes.include? selected
  exec "#{layout_path}/\"#{selected}\""
else
  puts modes.join("\n")
end
