#!/bin/bash

shorts_dir="$HOME/.myconfig/shorts"
shorts_files=$(find "$shorts_dir" -type f -executable)

if short=$(printf "%s" "$shorts_files" | sed -e 's/\.[a-zA-Z]*$//' -e 's|^'"$shorts_dir"'/\{0,1\}||g' | rofi -dmenu -p short); then
  shorts_file=$(printf "%s" "$shorts_files" | grep "$shorts_dir.*$short")
  $shorts_file
fi
